server:
  port: 8081

spring:
  application:
    name: user-server
  profiles:
    active: ${SPRING_PROFILE:local}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

grpc:
  server:
    port: 6565