jwt:
  secret:
    key: ${JWT_SECRET_KEY}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  datasource:
    url: jdbc:mysql://${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        instance-profile: true
      s3:
        bucket: couponmoa-user-profile-prod